### PR TITLE
Add UberHardcore scenario

### PR DESCRIPTION
**Pull request by D4mnX**
@Eluinhost I assume you're fine with this as https://github.com/Eluinhost/UberHardcore is published? If so, could that repo be officially licensed?

### CODE REVIEW

**Comment by Eluinhost** [comment]
You'll have to be really careful and do a lot of testing if you want to use this in a situation for turning on/off at will as it was designed for running all the time whilst installed and does really fucky things with NMS and has really high potential for invisible mobs if something goes wrong

I'll put up 1.0.1 licensed as MIT with headers setup to fix the license problem

**Comment by Eluinhost** [comment]
You probably want to revert this Leon as I dont think it actually does
anything as it hasnt been hooked in to anything and doesnt have licensed
attached, it was more of a 'wip' PR. D4 can reopen another PR with valid
content

**Comment by D4mnX** [comment]
I never "hook" the stuff in, I leave that to Leon as I don't fully understand his scenario stuff.

As for proper disabling, we found out that the listeners weren't being unregistered (makes sense, as Bukkit would handle that in a standalone plugin), so Leon just made sure to unregister all listeners from MobOverrides.

**Comment by Eluinhost** [comment]
oh god, think of the poor master branch! :P Fair enough then, @LeonTG77 all you need to do is hook it into your scenario stuff, add license and then hope the server doesn't explode when it's ran

**Comment by LeonTG77** [comment]
I didn't even look at your comments there and hosted a game with it without problems

**Comment by D4mnX** [comment]
> oh god, think of the poor master branch!

Implying Leon's master branch isn't 24/7/365 messed up anyways Kappa

**Pull request merged**
